=== gitGNU/gnu_x4o/x4o-driver/src/main/resources/META-INF/language/modules-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

    Copyright (c) 2004-2014, Willem Cazander
    All rights reserved.

    Redistribution and use in source and binary forms, with or without modification, are permitted provided
    that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the
      following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
      the following disclaimer in the documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
    EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
    THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
    OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
    HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
    TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<schema version="1.0" elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://language.x4o.org/xml/ns/modules"
	xmlns:this="http://language.x4o.org/xml/ns/modules"
	>
	<simpleType name="class-resource-type">
		<restriction base="string"/>
	</simpleType>
	<simpleType name="class-code-type">
		<restriction base="string"/>
	</simpleType>
	<complexType name="languageType">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="eld-resource" minOccurs="0" maxOccurs="unbounded" type="this:class-resource-type" />
			<element name="module-loader" minOccurs="0" maxOccurs="unbounded" type="this:class-code-type"/>
			<element name="elb-resource" minOccurs="0" maxOccurs="unbounded" type="this:class-resource-type"/>
			<element name="sibling-loader" minOccurs="0" maxOccurs="unbounded" type="this:class-code-type"/>
		</choice>
		<attribute name="version" type="string" use="required" />
	</complexType>
	<element name="modules">
		<complexType>
			<sequence>
				<element name="language" type="this:languageType" minOccurs="1" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="version" type="decimal" use="required" fixed="1.0"/>
		</complexType>
	</element>
</schema>

=== gitGNU/gnu_x4o/x4o-driver/src/test/resources/tests/modules/test-modules-full.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2004-2014, Willem Cazander
    All rights reserved.

    Redistribution and use in source and binary forms, with or without modification, are permitted provided
    that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the
      following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
      the following disclaimer in the documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
    EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
    THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
    OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
    HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
    TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<modules version="1.0"
	xmlns="http://language.x4o.org/xml/ns/modules"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://language.x4o.org/xml/ns/modules http://language.x4o.org/xml/ns/modules-1.0.xsd"
	>
	<language version="1.0">
		<eld-resource>my-lib0.eld</eld-resource>
		<eld-resource>my-lib1.eld</eld-resource>
		<eld-resource>my-lib2.eld</eld-resource>
		<eld-resource>my-lib3.eld</eld-resource>
		<eld-resource>my-lib4.eld</eld-resource>
		<eld-resource>my-lib5.eld</eld-resource>
		<eld-resource>my-lib6.eld</eld-resource>
		<eld-resource>my-lib7.eld</eld-resource>
		
		<elb-resource>my-bean0.elb</elb-resource>
		<elb-resource>my-bean1.elb</elb-resource>
		<elb-resource>my-bean2.elb</elb-resource>
		
		<module-loader>org.foo.bar.test.loader.FirstLoader</module-loader>
		<module-loader>org.foo.bar.test.loader.SecondLoader</module-loader>
		<module-loader>org.foo.bar.test.loader.LastLoader</module-loader>
		
		<sibling-loader>org.foo.bar.test.loader.OtherLanguageSiblingLoader</sibling-loader>
	</language>
</modules>
